### ISSUE TITLE
Framework fails on node 7.1 and phantomJS

### ISSUE THREAD

**Issue by AScripnic** [MitocGroup/deep-framework#490]
deep-framework is not working on node 7.1 on phantomJS with error: `TypeError: 'undefined' is not a function (evaluating 'require("./request").bind(null, Request)')`

**Comment by AScripnic** [comment]
With PhantomJS 2.0 is working

**Comment by eistrati** [comment]
Verified.
